name: Build XML feeds (multi-site)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */12 * * *"  # kør hver 12. time (UTC)

permissions:
  contents: write  # krævet for at kunne committe/pushe output

concurrency:
  group: build-xml-multi
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # <-- vigtigt ift. pull --rebase
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
        # requirements.txt skal indeholde: requests, beautifulsoup4, lxml

      - name: Generate XMLs
        run: |
          python multi_scraper_xml.py

      - name: Verify outputs
        run: |
          set -e
          test -f data_all.xml && echo "✅ data_all.xml OK" || (echo "❌ data_all.xml mangler" && exit 1)
          mkdir -p out
          ls -lah out || true

      - name: Commit XMLs
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update XML feeds"
            BRANCH="${GITHUB_REF_NAME:-main}"
            # sørg for vi kan rebase mod origin/BRANCH, selv ved schedule
            git fetch origin "$BRANCH"
            git pull --rebase --autostash origin "$BRANCH" || true
            git push origin "$BRANCH"
          fi

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: xml-output
          path: |
            data_all.xml
            out/*.xml
          if-no-files-found: warn
